version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    ports:
      - "0.0.0.0:3000:3000"
    volumes:
      - ./frontend:/app:Z
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=/api
      - WATCHPACK_POLLING=true
    user: "1000:1000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend
    volumes:
      - ./backend:/app:Z
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/portfolio
    depends_on:
      - db

  db:
    image: docker.io/library/postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: portfolio
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: docker.io/library/nginx:latest
    ports:
      - "0.0.0.0:8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro,Z
    depends_on:
      - frontend
      - backend

volumes:
  pgdata:
